# Generated by Django 6.0.2 on 2026-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_title',
            field=models.CharField(default='UnKnown', max_length=200),
            preserve_default=False,
        ),
    ]
