# Generated by Django 6.0.2 on 2026-02-13 15:30

import scanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_resume_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resumes/', validators=[scanner.models.validate_pdf]),
        ),
    ]
