# Generated by Django 6.0.2 on 2026-02-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_resume_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(default='processing', max_length=20),
        ),
    ]
