# Generated by Django 6.0.2 on 2026-02-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_resume_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(default='uploading', max_length=30),
        ),
    ]
