# Generated by Django 6.0.2 on 2026-02-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='missing_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
