# Generated by Django 6.0.2 on 2026-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_resume_missing_keywords_alter_resume_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='optimized_file',
            field=models.FileField(blank=True, null=True, upload_to='optimized/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='score_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
