# Generated by Django 6.0.2 on 2026-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_resume_expected_salary_resume_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience_years',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
